# server/my_server.py
from fastmcp import FastMCP
from haystack.components.websearch.serper_dev import SerperDevWebSearch
from haystack.utils import Secret
import os
from dotenv import load_dotenv
from pathlib import Path
import threading
import time
import json
import uuid
from collections import OrderedDict

# Haystack Imports
from haystack import Pipeline
from haystack.components.embedders import OpenAITextEmbedder
from haystack_integrations.components.retrievers.chroma import ChromaEmbeddingRetriever
from haystack_integrations.document_stores.chroma import ChromaDocumentStore

load_dotenv()

# --- Configuración Inicial ---
SERVER_DIR = Path(__file__).parent
DB_PATH = str(SERVER_DIR / "knowledge" / "chroma_db_data")

# FIX #2: Cache con límite de tamaño usando OrderedDict (LRU manual)
MAX_CACHE_SIZE = 100
_document_cache = OrderedDict()
_cache_lock = threading.Lock()

mcp = FastMCP("StudentKnowledgeTools")

# Inicialización de Componentes
document_store = ChromaDocumentStore(
    persist_path=DB_PATH, 
    collection_name="reddit_datascience_openai"
)

query_pipeline = Pipeline()
query_pipeline.add_component("text_embedder", OpenAITextEmbedder(model="text-embedding-3-small"))
query_pipeline.add_component("retriever", ChromaEmbeddingRetriever(document_store=document_store))
query_pipeline.connect("text_embedder.embedding", "retriever.query_embedding")

try:
    web_search_component = SerperDevWebSearch(
        api_key=Secret.from_env_var("SERPER_API_KEY"),
        top_k=5
    )
except Exception:
    web_search_component = None

def _cache_docs(call_id: str, query: str, tool_name: str, documents):
    """
    FIX #1: Ahora usa call_id único para correlación exacta
    FIX #2: Implementa LRU limitando a MAX_CACHE_SIZE entradas
    """
    timestamp = time.time()
    
    serializable_docs = []
    for doc in documents:
        serializable_docs.append({
            "content": doc.content,
            "metadata": dict(doc.meta),
            "score": float(doc.score) if doc.score is not None else 0.0,
            "id": doc.id
        })
        
    with _cache_lock:
        # Añadir nueva entrada
        _document_cache[call_id] = {
            "call_id": call_id,
            "tool": tool_name,
            "query": query,
            "documents": serializable_docs,
            "timestamp": timestamp
        }
        
        # Limitar tamaño del cache (eliminar más antiguos)
        while len(_document_cache) > MAX_CACHE_SIZE:
            _document_cache.popitem(last=False)  # FIFO: elimina el primero

    return call_id  # Devolver el ID para que el cliente lo use

@mcp.tool
def search_knowledge_base(query: str, call_id: str = None) -> str:
    """
    Searches the internal Knowledge Base (Reddit Data Science Archive).
    
    Args:
        query: The search query
        call_id: Unique identifier for this tool call (generated by client)
    """
    # FIX #1: Generar call_id si no se proporciona (backward compatibility)
    if not call_id:
        call_id = str(uuid.uuid4())
    
    print(f"--- [RAG] Query: {query} | CallID: {call_id} ---")
    
    try:
        result = query_pipeline.run({
            "text_embedder": {"text": query},
            "retriever": {"top_k": 5}
        })
        
        documents = result["retriever"]["documents"]
        
        # Guardar en caché con el call_id
        _cache_docs(call_id, query, "search_knowledge_base", documents)
        
        if not documents:
            return json.dumps({"call_id": call_id, "result": "No relevant information found."})
            
        formatted_response = "Context from Knowledge Base:\n\n"
        for idx, doc in enumerate(documents):
            score = doc.score if doc.score else 0.0
            formatted_response += (
                f"--- Result {idx + 1} ---\n"
                f"Content: {doc.content}\n"
                f"Score: {score:.4f}\n\n"
            )
        
        # Devolver JSON con call_id para correlación
        return json.dumps({
            "call_id": call_id,
            "result": formatted_response
        })

    except Exception as e:
        return json.dumps({"call_id": call_id, "error": str(e)})

@mcp.tool
def search_web(query: str, call_id: str = None, top_k: int = 5) -> str:
    """
    Searches the real-time web using Google.
    
    Args:
        query: The search query
        call_id: Unique identifier for this tool call
        top_k: Number of results to return
    """
    if not call_id:
        call_id = str(uuid.uuid4())
        
    print(f"--- [WEB] Query: {query} | CallID: {call_id} ---")
    
    if not web_search_component:
        return json.dumps({"call_id": call_id, "error": "Web search tool not configured."})

    try:
        results = web_search_component.run(query=query)
        documents = results["documents"][:top_k]
        
        _cache_docs(call_id, query, "search_web", documents)
        
        if not documents:
            return json.dumps({"call_id": call_id, "result": "No web results found."})
        
        formatted = ""
        for idx, doc in enumerate(documents):
            formatted += f"--- Web {idx+1} ---\nTitle: {doc.meta.get('title')}\nLink: {doc.meta.get('link')}\nSnippet: {doc.content}\n\n"
        
        return json.dumps({
            "call_id": call_id,
            "result": formatted
        })

    except Exception as e:
        return json.dumps({"call_id": call_id, "error": str(e)})

@mcp.tool
def get_cached_documents(call_ids: list[str]) -> str:
    """
    FIX #1: Recupera documentos específicos por call_id (no por ventana de tiempo genérica)
    
    Args:
        call_ids: Lista de IDs de llamadas a herramientas
    """
    results = []
    
    with _cache_lock:
        for call_id in call_ids:
            if call_id in _document_cache:
                results.append(_document_cache[call_id])
    
    return json.dumps(results)

if __name__ == "__main__":
    mcp.run(transport="http", port=8000)